version: 2

build:
  os: ubuntu-22.04

  tools:
    python: "3.10"

  apt_packages:
    - git
    - curl
    - gcc
    - automake
    - autoconf
    - libtool
    - libcurl4-openssl-dev
    - libsodium-dev
    - libssl-dev
    - libcrypto++-dev
    - libc-ares-dev
    - swig
    - libpthread-stubs0-dev
    - zlib1g-dev

  jobs:
    pre_build:
      - git submodule init
      - git submodule update
      - sh configure.sh
      - pip install -e .