# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install Mega SDK enviroment
      run: |
        sudo apt-get install -y wget curl pv jq \
        locales unzip mediainfo git make g++ gcc automake \
        autoconf libtool libcurl4-openssl-dev \
        libsodium-dev libssl-dev libcrypto++-dev libc-ares-dev \
        swig libpthread-stubs0-dev zlib1g-dev \
        python3-distutils

    - name: Install dependencies
      run: |
        python -m ensurepip --default-pip
        pip install build setuptools wheel

    - name: Prepare enviroment
      run: |        
        sh configure.sh

    - name: Build package
      run: python -m build --wheel --no-isolation    

    - name: Archive package
      uses: actions/upload-artifact@v3
      with:
        name: aiomega-wheels
        path: dist/*.whl

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
